services:
  frontend:
    image: vadimzaicev/cloudfilestorage_frontend
    restart: unless-stopped
    container_name: frontend_container
    ports:
      - "80:80"
  db:
    image: postgres:14.17
    restart: unless-stopped
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: file_storage
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
  redis:
    image: redis:7.4.2
    restart: unless-stopped
    container_name: redis_container
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio_containger
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
volumes:
  pg_data:
  redis_data:
  minio_data: